### PR TITLE
ntp client support authen

### PR DESCRIPTION
**Pull request by silves-xiang**
latest day , i need to write a go client to sync authentication ntp server time, but this package can't support authen, so i study some ntp authentication,  modify and  add some code , base on this package

### CODE REVIEW

**Comment by silves-xiang** [comment]
At first I modified the go mod file, but the later commits have been modified back

**Comment by beevik** [comment]
Thank you for the pull request.

I have a couple of questions.

1. In your implementation, a message digest is computed by the client before the NTP request is sent to the server.  But the server's response, which should also have a MAC, is not authenticated. Isn't the purpose of adding authentication to verify that the server is responding with an authenticated message?
2. Your authentication scheme includes the "CryptoMethod" and "Authentication" string when calculating the digest. From my reading of the RFC, the digest should cover only the NTP header and the Key ID field.  Also, what is the "Authentication" string?
3. Your code appears to send the digest before the NTP header. Shouldn't it be the other way around?
4. There are no unit tests. I would like to see the code working with an actual NTP server.

**Comment by silves-xiang** [comment]
> Thank you for the pull request.
> 
> I have a couple of questions.
> 
> 1. In your implementation, a message digest is computed by the client before the NTP request is sent to the server.  But the server's response, which should also have a MAC, is not authenticated. Isn't the purpose of adding authentication to verify that the server is responding with an authenticated message?
> 2. Your authentication scheme uses the "Authentication" string when calculating the digest. From my reading of the RFC, the digest should cover only the NTP header and extension fields. What is this "Authentication" string?
> 3. Your code appears to send the digest before the NTP header. Shouldn't it be the other way around?
> 4. There are no unit tests. I would like to see the code working with an actual NTP server.
> 
> EDIT:
> 
> Ok I have done more research on NTP authentication. (I was not familiar with it before, and I could still be wrong about many things.)
> 
> On point 2, I see that the "Authentication" field probably refers to the key shared by the NTP client and server, and the digest is computed over the concatenation of the key and the NTP header contents.
> 
> On point 3, I see that your code is actually appending the digest to the buffer. I was confused because the name of the `writeAuthenMsgToConn` function implied that the data was being written directly to the connection (instead of to the buffer via an `io.Writer`).
> 
> On point 4, this request for unit tests is probably going to be difficult, because the NTP scheme is symmetric and requires sharing of keys between the client and server.

谢谢你的恢复，上面我提交的代码仍然有很多错误，针对您提出的问题，我有如下回答，我的英语不好，都是使用翻译软件翻译的，请您见谅。
选项2：确实没有对ntp返回的数据进行校验，后期再次提交的时候，我会将响应体的校验添加上去。
选项3：对于命名问题，writeAuthenMsgToConn，该接口只是写入buf，没有写入con，这里的命名问题，我将会再下次提交时修改。

对于您提出的问题，我将会重新提交

**Comment by silves-xiang** [comment]
Add authentication for ntp package to me, it has been tested successfully, I will improve and modify some existing problems according to your questions

**Comment by beevik** [comment]
I incorporated your changes into a new branch and added additional code to support some of the changes I requested:

https://github.com/beevik/ntp/tree/add-auth

Please take a look. Thank you.

**Comment by silves-xiang** [comment]
> I incorporated your changes into a new branch and added additional code to support some of the changes I requested: > > https://github.com/beevik/ntp/tree/add-auth > > Please take a look. Thank you.

OK, I'll look at the new branch and get back to you around noon BST, thanks for your feedback.

**Pull request closed without merging**
